### ISSUE TITLE
Greenwald-khanna extension

### ISSUE THREAD

**Issue by Albibek** [postmates/quantiles#20]
Hi.

If it is this possible to merge two Greenwald-khanna streams together, like it is done in CKMS AddAssign impl? Could this be implemented, please?

Serialize-deserialize for this structure could also be great.

**Comment by blt** [comment]
@Albibek hello! I'm not sure, not having studied the GK algorithm in depth as I have the CKMS. That said, I'd be very happy to review any patches you might put together. I _bet_ there's a straightforward way to merge them.

**Comment by sitegui** [comment]
Hello,

I've recently contributed to Apache Spark an algorithm to merge two GK Summaries built from independent streams (but with the same epsilon):
https://github.com/apache/spark/blob/02af468b8c249103e65e97ce0945309e0d48e1a3/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/QuantileSummaries.scala#L153-L229

I could do a PR with a Rust equivalent.
@blt , would this feature be welcomed?

**Comment by blt** [comment]
It absolutely would be. Thank you for the offer!

- blt
