### ISSUE TITLE
`CKMS::query` documentation is incomplete

### ISSUE THREAD

**Issue by vks** [postmates/quantiles#22]
It is not documented what the function returns.

**Comment by blt** [comment]
The current docs are here: https://docs.rs/quantiles/0.7.0/quantiles/ckms/struct.CKMS.html#method.query and read

> Query CKMS for a ε-approximate quantile
> 
> This function returns an approximation to the true quantile-- +/- εΦn --for the points inserted. Argument q is valid 0. <= q <= 1.0. The minimum and maximum quantile, corresponding to 0.0 and 1.0 respectively, are always known precisely.

Both a touch dense and missing an explanation of what each of the elements of `(usize, T)` mean. The first element is the `r_i` of the CKMS paper, which the authors call "an overly conservative bound on the rank of the item v". How does this rewrite strike you:

> This function returns an approximation to the true quantile-- +/- εΦn --for the points inserted. Argument q is valid 0. <= q <= 1.0. The first element of the return tuple is the rank estimation for q, the second element is the quantile estimation for q. The minimum and maximum quantile, corresponding to 0.0 and 1.0 respectively, are always known precisely.

**Comment by vks** [comment]
Sounds good to me! :+1:

**Comment by blt** [comment]
Cool. I'll update the language in the docs here in a few hours. Thanks!
