### ISSUE TITLE
Security review notes for followup

### ISSUE THREAD

**Issue by randomdross** [postmates/quantiles#24]
Hi @blt, as requested I'm including security review notes here. (I'm not particularly Rust-savvy at the moment, so some of this may not be interesting in reality.) PTAL and assess if there's anything worth following up on.

---
  - Good to see fuzzing in place, though I’m only just now learning about memory safety w.r.t. Rust.  Looks like Rust is only unsafe in places explicitly marked as unsafe, but I don’t see this in the code.  Any further context on the fuzzing would be interesting to hear about.
---

**Comment by blt** [comment]
@randomdross please see comment on https://github.com/postmates/hopper/issues/22
